logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: eatda-storage-dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  config:
    import: "aws-parameterstore:/dev/"

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations:
      - classpath:db/migration
      - classpath:db/seed/dev

jwt:
  access-token-expiration: 1h
  refresh-token-expiration: 14d
  secret-key: ${JWT_SECRET_KEY}

cors:
  origin:
    - "http://localhost:3000"
    - "https://api-dev.eatda.net"

oauth:
  client-id: ${OAUTH_CLIENT_ID}
  redirect-path: /login/callback
  allowed-origins:
    - "http://localhost:3000"
    - "https://dev.eatda.net"

kakao:
  api-key: ${KAKAO_API_KEY}
